export const item = [
  {
    id: Math.random(),
    title: "PIZZA",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Breakfast",
    img: "./assets/img/pizza.jpg",
  },
  {
    id: Math.random(),
    title: "SOUP",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Dinner",
    img: "./assets/img/soup.jpg",
  },
  {
    id: Math.random(),
    title: "PASTA",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Lunch",
    img: "./assets/img/pasta.jpg",
  },
  {
    id: Math.random(),
    title: "BOURGER",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Breakfast",
    img: "./assets/img/burger.jpg",
  },
  {
    id: Math.random(),
    title: "JUICE",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Breakfast",
    img: "./assets/img/juice1.jpg",
  },
  {
    id: Math.random(),
    title: "JUICE",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Breakfast",
    img: "./assets/img/juice2.jpg",
  },
  {
    id: Math.random(),
    title: "JUICE",
    description: "lorem lorem lorem ",
    price: "1 OR",
    category: "Breakfast",
    img: "./assets/img/juice3.jpg",
  },
];
